% Source: Krzysztof Apt. Principles of Constraint Programming. Chapter 2. 2003

% Exercise 2.8 Peaceable Coexisting Armies of Queens.

% Two armies of queens (black and white) peacefully coexist on a chessboard
% when they are placed upon the board in such a way that no two queens
% from opposing armies can attack each other. The problem is to find the
% maximum two equal-sized armies. Formulate this problem as a constrained
% optimization problem.
