% Source: Krzysztof Apt. Principles of Constraint Programming. Chapter 2. 2003

% Exercise 2.3 Magic Squares.

% A magic square of order n is defined to be an n × n matrix made out
% of the integers from [1..n 2 ] arranged in such a way that the sum of every
% row, column, and the two main diagonals is the same. For example

% 1 15 24 8 17
% 23 7 16 5 14
% 20 4 13 22 6
% 12 21 10 19 3
% 9 18 2 11 25

% is a magic square of order 5, because each row, column and main diagonal
% sums up to 65. Formulate the problem of finding a magic square of order n
% as a task of finding a solution to a CSP.
